#
#  Backend
#

# Cache for Maven (.m2 repository)
cache:
  image: busybox
  volumes:
   - ./cache/.m2/repository:/root/.m2/repository

# Backend:: Project CodeBase
sources:
  image: busybox
  volumes:
   - .:/myproject

# Backend:: Build project
build:
  image: maven:3.2.3-jdk-8
  command: mvn clean package -DfinalName=usopen
  volumes_from:
   - cache
   - sources
  working_dir: /myproject
  environment:
    MAVEN_OPTS: -Xshare:auto -Xms128M -Xmx1G

# Backend:: Run Backend
deploy:
  build: .
  ports:
    - "8080:8080"
  volumes:
    - ./target/usopen/:/opt/jboss/wildfly/standalone/deployments/ROOT.war/
